### ISSUE TITLE
Bug $i++ convert to $i

### ISSUE THREAD

**Issue by iyasilias** [LukasMeine/devmind-beautifier#3]
This is my code:
```
        $i = 1;

        foreach ($files as $f)
        {
            rename($this->folderName . "/" . $this->filePrefix . $f, $this->folderName . "/" . $renamedPrefix . "_" . $this->matricNo . "(" . $i++ . ")." . $this->ext);
        }
```

When using your package, the **`$i++`** was changed to **`$i`**

I like your package!

**Comment by LukasMeine** [comment]
Hi! I'm completely remaking this package and this issue is going to get fixed soon.
Check it out here: https://github.com/LukasMeine/universal-code-beautifer
